# Generated by Django 4.2.6 on 2023-11-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='item',
            name='course',
            field=models.CharField(choices=[('1 курс бакалавру', '1 курс бакалавру'), ('2 курс бакалавру', '2 курс бакалавру'), ('3 курс бакалавру', '3 курс бакалавру'), ('4 курс бакалавру', '4 курс бакалавру'), ('Інше', 'Інше')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.category'),
        ),
    ]
