# Generated by Django 3.2.23 on 2023-11-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
